BlogComputerScience/Controllers/ArticleController.cs
using BlogComputerScience.Database;
using BlogComputerScience.Models;
using BlogComputerScience.Models.ModelForViews;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BlogComputerScience.Controllers
{
    [Authorize]
    public class ArticleController : Controller
    {
        public IActionResult Index()
        {
            using (BlogContext db = new BlogContext())
            {
                List<Article> ourTecArticles = db.Articles.ToList();
                return View("Index", ourTecArticles);
            } 
        }

        public IActionResult Details(int id)
        {
            using(BlogContext db = new BlogContext())
            {
                Article? articleDetails = db.Articles.Where(article => article.Id == id).FirstOrDefault();

                if (articleDetails != null)
                {
                    return View("Details", articleDetails);
                } else
                {
                    return NotFound($"L'articolo con id {id} non è stato trovato!");
                }
            }

        }

        [Authorize(Roles = "ADMIN")]
        // ACTIONS PER LA CREAZIONE DI UN ARTICOLO
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "ADMIN")]
        public IActionResult Create(Article newArticle)
        {
            if (!ModelState.IsValid)
            {
                return View("Create", newArticle);
            }

            using (BlogContext db = new BlogContext())
            {
                db.Articles.Add(newArticle);
                db.SaveChanges();

                return RedirectToAction("Index");
            }

        }

        // ACTIONS PER LA MODIFICA DI UN ARTICOLO
        [HttpGet]
        [Authorize(Roles = "ADMIN")]
        public IActionResult Update(int id)
        {
            using(BlogContext db = new BlogContext())
            {
                Article? articleToModify = db.Articles.Where(article => article.Id == id).FirstOrDefault();

                if(articleToModify != null)
                {
                    return View("Update", articleToModify);
                } else {

                    return NotFound("Articolo da modifcare inesistente!");
                }
            }
            
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "ADMIN")]
        public IActionResult Update(int id, Article modifiedArticle)
        {
            if(!ModelState.IsValid)
            {
                return View("Update", modifiedArticle);
            }

            using(BlogContext db = new BlogContext())
            {
                Article? articleToModify = db.Articles.Where(article => article.Id == id).FirstOrDefault();

                if(articleToModify != null) { 
                
                    articleToModify.Title = modifiedArticle.Title;
                    articleToModify.Description = modifiedArticle.Description;
                    articleToModify.Image = modifiedArticle.Image;

                    db.SaveChanges();
                    return RedirectToAction("Index");

                } else
                {
                    return NotFound("L'articolo da modificare non esiste!");
                }
            }

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "ADMIN")]
        public IActionResult Delete(int id)
        {
            using(BlogContext db = new BlogContext())
            {
                Article? articleToDelete = db.Articles.Where(article => article.Id == id).FirstOrDefault();

                if(articleToDelete != null)
                {
                    db.Remove(articleToDelete);
                    db.SaveChanges();

                    return RedirectToAction("Index");

                } else
                {
                    return NotFound("Non ho torvato l'articolo da eliminare");

                }
            }
        }


        public IActionResult FindArticles(string titleKeyword, int viewCount)
        {
            UserProfile connectedProfile = new UserProfile("Bryan", "Lucchetta", 26);

            using (BlogContext db = new BlogContext())
            {
                List<Article> matchTitleArticles = db.Articles.Where(article => article.Title.Contains(titleKeyword)).ToList();

                ProfileListArticles resultModel = new ProfileListArticles(connectedProfile, titleKeyword, matchTitleArticles);


                return View("SearchArticles", resultModel);
            }
        }
    }
}

BlogComputerScience/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;

using BlogComputerScience.Database;
using BlogComputerScience.Models;
using Microsoft.EntityFrameworkCore;

namespace BlogComputerScience.Controllers
{
    public class ProductController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            List<Product> productList = new List<Product>();
             
            using (BlogContext db = new BlogContext())
            {

                productList = db.Products.OrderBy(p => p.Ranking).ToList();
                //TODO: ndsaybedybes dhsbeuybs edfdhsebdu

            }

            return View("Index", productList);
        }

        public IActionResult Details(int id)
        {
            using (BlogContext db = new BlogContext())
            {
                Product? ProductDetails = db.Products.Where(product => product.Id == id).Include(product => product.Category).FirstOrDefault();
                if(ProductDetails != null)
                {
                    return View("Details", ProductDetails);
                }
                
            }

			return NotFound($"l'articolo con in {id} non  è stato trovato!");

		}
            


         [HttpGet]
         public IActionResult Create()
         {
            return View("Create");
         }   


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Product NewProduct)
        {
            if (!ModelState.IsValid)
            {
                return View("Create", NewProduct);
            }

            using(BlogContext db = new BlogContext())
            {
                db.Products.Add(NewProduct);
                db.SaveChanges();
                //TODO: ndsaybedybes dhsbeuybs edfdhsebdu
                return RedirectToAction("Index");
            }
        }

        [HttpGet]
        public IActionResult Update(int id)
        {
            using(BlogContext db = new BlogContext())
            {
                Product? productToEdit = db.Products.Where(product => product.Id == id).FirstOrDefault();
                if(productToEdit == null)
                {
                    return NotFound("Il prodotto non è stato trovato");
                } else
                {
                    return View(productToEdit);
                }
            }
        }

        [HttpPost]      
        [ValidateAntiForgeryToken]
        public IActionResult Update(int id, Product updatedProduct)
        {
            if(!ModelState.IsValid)
            {
                //TODO: ndsaybedybes dhsbeuybs edfdhsebdu
                return View("Create", updatedProduct);
            } else
            {
                using(BlogContext db = new BlogContext())
                {   

                    Product? productToUpdate = db.Products.Where(product => product.Id == id).FirstOrDefault();
                    if(productToUpdate == null)
                    {
                        return NotFound("Il prodotto non è stato trovato");
                    } else
                    {
                        productToUpdate.Name = updatedProduct.Name;
                        productToUpdate.Description = updatedProduct.Description;
                        productToUpdate.ImgUrl = updatedProduct.ImgUrl;
                        productToUpdate.Ranking = updatedProduct.Ranking;
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                   
                    
                                      
                }
            }
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id)
        {
            using (BlogContext db = new BlogContext()) 
            {
                Product? ProductToDelete = db.Products.Where(product => product.Id == id).FirstOrDefault();

                    if (ProductToDelete != null)
                    {
                        db.Remove(ProductToDelete);
                        db.SaveChanges();

                        return RedirectToAction("Index");
                    }
                    else
                    {
                        return NotFound("Il prodotto non è stato trovato");
                    }
             }
        }
       



    }
}

BlogComputerScience/Views/Shared/_Footer.cshtml
<div class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 mx-2 border-top">
    <p class="col-md-4 mb-0 text-body-secondary">© 2023 Bryan, Inc</p>

    <a href="@Url.Action("Index", "Home")" class="col-md-4 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
        <img src="https://cdn-icons-png.flaticon.com/128/1865/1865273.png"
             alt="Logo"
             height="40px"
             class="d-inline-block align-text-top me-3" />
    </a>

    <ul class="nav col-md-4 justify-content-end">
        <li class="nav-item"><a href="@Url.Action("Contacts", "Home")" class="nav-link px-2 text-body-secondary">Contatti</a></li>
        <li class="nav-item"><a href="@Url.Action("Privacy", "Home")" class="nav-link px-2 text-body-secondary">Privacy</a></li>
    </ul>
</div>

BlogComputerScience/Views/Shared/_Header.cshtml
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <button class="navbar-toggler"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarNav"
                aria-controls="navbarNav"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse d-flex justify-content-center align-items-center" id="navbarNav">
            <ul class="navbar-nav d-flex justify-content-start align-items-center gap-5">
                <li class="nav-item">
                    <a href="@Url.Action("Index", "Home")" class="fixed">
                        <img src="/assets/img/logo-no-background.png" style="height: 128px;" />
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link fs-5 text-black" aria-current="page" href="@Url.Action("Index", "Home")">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link fs-5 text-black" href="@Url.Action("Index", "Article")">News</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link fs-5 text-black" href="@Url.Action("Index", "Product")">Prodotti</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link fs-5 text-black" href="@Url.Action("Contacts", "Home")">Contatti</a>
                </li>
                <partial name="_LoginPartial" />
            </ul>
        </div>
    </div>
</nav>

BlogComputerScience/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BlogComputerScience</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BlogComputerScience.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BlogComputerScience</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - BlogComputerScience - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BlogComputerScience/Views/Shared/_MioLayout.cshtml
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Computer Science Blog</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link href="~/css/site.css" rel="stylesheet" />
</head>
<body>

    <header>
        @Html.Partial("_Header");
    </header>

    <main>
        <!-- Qui sto informando Razor e gli sto dicendo che in questo punto voglio che
        mi copi tutto il codice della vista che il browser vuole vedere -->
        @RenderBody();

    </main>

    <footer>
        @Html.Partial("_Footer");
    </footer>

    <script src="~/js/site.js"></script>
    <!-- Predispongo un segnaposto per poter inserire degli eventuali script -->
    @RenderSection("ScriptSection", required: false)
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
</body>
</html>